apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: appscrp
spec:
  policy:
    placementType: PickN
    numberOfClusters: 1
    affinity:
      clusterAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              propertySorter:
                name: kubernetes-fleet.io/node-count
                sortOrder: Descending
  resourceSelectors:
    - group: ""
      kind: Namespace
      name: apps
      version: v1
