apiVersion: placement.kubernetes-fleet.io/v1
kind: ClusterResourcePlacement
metadata:
  name: appscrp
spec:
  resourceSelectors:
    - group: ''
      kind: Namespace
      name: apps
      version: v1
