apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerdemo
  namespace: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dockerdemo
  strategy: {}
  template:
    metadata:
      labels:
        app: dockerdemo
    spec:
      containers:
      - image: binarydad/dockerdemo:latest
        name: dockerdemo
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: dockerdemo
  namespace: apps
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dockerdemo
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: dockerdemo
#   namespace: apps
#   # annotations:
#   #   appgw.ingress.kubernetes.io/cookie-based-affinity: "true"
# spec:
#   ingressClassName: nginx
#   rules:
#   - http:
#       paths:
#       - path: /
#         backend:
#           service:
#             name: dockerdemo
#             port:
#               number: 80
#         pathType: Prefix